### ISSUE TITLE
Add some "pizazz"

### ISSUE THREAD

**Issue by joshburer** [dwburer/danielburer.com#29]
Tried to open a PR but I can't create a branch so I'm gonna manually write my changes here:

## Description

There is a problem with your site. It does not contain enough "hustle and bustle".

## Steps to Reproduce
1. Open the website
2. See that it does not contain a lot of life or movement
3. weep

## Expected Behavior
The website should make me feel better than it does.

## Proposed Solution

In `strings.js`:

```javascript
// ... line 5...
homepage: {
    title: 'Daniel Burer',
    line1: 'software engineer',
    line2: 'digito cweative',  // Changed this
    line3: 'designer',
  },
  about: {  // Changed this section
    headline:
      "Hey, I’m Daniel (or you might know me as Danny!). Right now I'm working as a software engineer @Striposoft.",
    headline_linkMeta: {
      '@Striposoft': 'https://www.stripe.com/',
    },
```

A few other minor improvements to improve accessibility:

In `styles.scss` (just append to the bottom):
```scss
/* Hmm.... Could use a little more movement to make things pop... */
@keyframes spin-the-whole-thang {
    0% {
        transform: rotate(0deg);
    }

    100% {
        transform: rotate(360deg);
    }
}

html {
    animation: 300s ease-in-out spin-the-whole-thang;
}
```

---

I deeply appreciate the time and effort the maintainers put into this project. It's a critical resource for many, and I am truly grateful for the opportunity to contribute and help improve it. Thank you for considering my contribution and taking the time to review this issue.
